buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
staticRoutes:
  - from: /config-yaml-static
    to: /locations/7751-bird-rd
    status: 301
dynamicRoutes:
  - from: /origin/:category/dynamic
    to: /destination/dynamic/:category
    status: 302